name: Create New Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Use Xcode 16.2
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Compile Feather
        run: | 
          agvtool new-version -all $(git rev-parse HEAD)
          sed -i '' -E "s/(\t*MARKETING_VERSION *= *)[^ ;]+(;)/\1${{ github.event.inputs.version }}\2/" ./Feather.xcodeproj/project.pbxproj
          make
          mkdir upload
          mv packages/* upload/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Feather v${{ github.event.inputs.version }}
          tag_name: v${{ github.event.inputs.version }}
          files: |
            upload/*ipa
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
